---
stages:
  - build

image: docker:stable-git

.build_template:
  stage: build
  tags: ['docker-build']
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - apk add bash
  script:
    - ./build_images.sh -i $CI_REGISTRY_IMAGE -d $CI_PROJECT_DIR -t $CI_COMMIT_SHORT_SHA $EXTRA_TAG
  only:
    - branches

Build:
  extends: .build_template

Build Tagged:
  extends: .build_template
  variables:
    EXTRA_TAG: "-t $CI_COMMIT_TAG"
  only:
    - tags

Build serverspec:
  extends: .build_template
  script:
    - ./build_images.sh -i $CI_REGISTRY_IMAGE/serverspec -d $CI_PROJECT_DIR/spec -t $CI_COMMIT_SHORT_SHA

specs:
